In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pickle

In [2]:
df = pd.read_csv('saved_dataframe/df_with_6h_future_ready_to_train_23_12_20.csv')
print(df)

       Humidity  Temperature  Hour  Minute  Humidity_Future  \
0          72.0         34.6  15.0    42.0             80.0   
1          66.0         34.6  15.0    42.0             80.0   
2          66.0         34.6  15.0    42.0             81.0   
3          66.0         34.6  15.0    43.0             81.0   
4          66.0         34.6  15.0    43.0             81.0   
...         ...          ...   ...     ...              ...   
11401      71.0         33.9   6.0    40.0             62.0   
11402      72.0         34.2   6.0    41.0             62.0   
11403      70.0         34.3   6.0    41.0             62.0   
11404      69.0         34.8   6.0    41.0             62.0   
11405      69.0         34.9   6.0    41.0             63.0   

       Temperature_Future  Hour_Future  Minute_Future  
0                    30.3         21.0           42.0  
1                    29.9         21.0           42.0  
2                    29.9         21.0           42.0  
3                  

In [3]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()


In [4]:
X = df[['Humidity', 'Temperature', 'Hour', 'Minute']]
y = df['Temperature_Future']

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [7]:
X_train_scaled = pd.DataFrame(scaler.fit_transform(X_train[X_train.columns]), columns = X_train.columns)
X_test_scaled = pd.DataFrame(scaler.fit_transform(X_test[X_test.columns]), columns = X_test.columns)

In [9]:
X_train_scaled

Humidity  Temperature      Hour    Minute
0    -1.762215     2.255557  0.457021 -0.538982
1    -0.617189     0.333499  0.198729  0.972413
2    -1.876717     2.344955  0.327875  1.611849
3     0.527836    -0.471084 -0.963583 -1.469071
4    -0.846194     0.601693  0.198729 -1.352810
...        ...          ...       ...       ...
9119  0.985846    -0.739278  1.231896 -1.004027
9120 -0.273682    -0.471084  1.231896 -0.364590
9121 -0.502687    -0.158191  1.102750 -1.585332
9122 -1.189702     1.316877  0.715312 -0.538982
9123 -1.762215     2.076761  0.457021 -1.004027

[9124 rows x 4 columns]

In [2]:
from sklearn.linear_model import LinearRegression

In [30]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [31]:
model.score(X_test, y_test)

0.7215171814975577

Support Vector Regression

In [9]:
from sklearn.svm import SVR
svr_lin = SVR(kernel='linear', C=1e4)

In [ ]:
svr_model = svr_lin.fit(X_train, y_train)

In [11]:
svr_pred = y_lin.predict(X_test)

In [15]:
svr_pred

array([ -284.19910571,  -742.06249163, -1254.99770758, ...,
        -796.93400606,   392.58539918,    22.03499511])

In [16]:
y_test

6440     29.9
2678     27.8
1371     29.6
10655    26.8
11738    34.8
         ... 
9805     26.5
9285     27.1
2928     28.2
510      32.4
9490     26.5
Name: Temperature_Future, Length: 2385, dtype: float64

In [15]:
loaded_model = pickle.load(open('Pickle_RL_Model.pkl', 'rb'))


In [16]:
loaded_model.predict(X_test)

array([-0.51399159,  0.88714899,  0.46526038, ..., -0.07681337,
       -1.45318206,  1.63909216])

In [10]:
from sklearn import model_selection
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.linear_model import ElasticNet
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt

In [11]:
rr = Ridge(alpha=0.01)
rr.fit(X_train_scaled, y_train) 
pred_train_rr= rr.predict(X_train_scaled)
print(mean_squared_error(y_train, pred_train_rr))
print(r2_score(y_train, pred_train_rr))

pred_test_rr= rr.predict(X_test_scaled)
print(mean_squared_error(y_test,pred_test_rr)) 
print(r2_score(y_test, pred_test_rr))

1.7600309343173677
0.816073311272762
1.741561747273706
0.8134774473019187


In [12]:
pred_train_rr

array([28.21840012, 29.26044574, 28.66259324, ..., 26.67557439,
       27.72880929, 28.08380304])

In [13]:
y_train

213     27.8
6430    28.9
81      28.5
4337    34.2
6195    29.2
        ... 
2051    28.7
9071    26.0
8601    26.5
711     27.5
163     28.2
Name: Temperature_Future, Length: 9124, dtype: float64

In [14]:
model_lasso = Lasso(alpha=0.01)
model_lasso.fit(X_train_scaled, y_train) 
pred_train_lasso= model_lasso.predict(X_train_scaled)
print(mean_squared_error(y_train, pred_train_lasso))
print(r2_score(y_train, pred_train_lasso))

pred_test_lasso= model_lasso.predict(X_test_scaled)
print(mean_squared_error(y_test, pred_test_lasso))
print(r2_score(y_test, pred_test_lasso))

1.762131097101556
0.8158538401378221
1.7400595507319172
0.813638333663868


In [16]:
model_enet = ElasticNet(alpha = 0.01)
model_enet.fit(X_train_scaled, y_train) 
pred_train_enet= model_enet.predict(X_train_scaled)
print(mean_squared_error(y_train, pred_train_enet))
print(r2_score(y_train, pred_train_enet))

pred_test_enet= model_enet.predict(X_test_scaled)
print(mean_squared_error(y_test,pred_test_enet))
print(r2_score(y_test, pred_test_enet))

1.7615758758703912
0.815911861846741
1.7396066149217644
0.8136868434245182
